package view;

import model.domain.Funcionario;
import model.domain.TipoUsuario;

public class TelaPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName());

    private Funcionario funcionarioLogado;
    
    public TelaPrincipalFrame(Funcionario funcionario) {
        initComponents();
        setLocationRelativeTo(null);
        this.funcionarioLogado = funcionario;
        boolean isAdmin = this.funcionarioLogado.getTipoUsuario() == TipoUsuario.ADMINISTRADOR;
        menuItemFuncionarios.setVisible(isAdmin);
        menuItemMercadorias.setVisible(isAdmin);
        menuRelatorios.setVisible(isAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuCRUDs = new javax.swing.JMenu();
        menuItemFuncionarios = new javax.swing.JMenuItem();
        menuItemMercadorias = new javax.swing.JMenuItem();
        menuItemSenha = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuItemRelatorioEstoque = new javax.swing.JMenuItem();
        menuItemRelatoriovendas = new javax.swing.JMenuItem();
        menuItemRelatorioFinanceiro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        menuCRUDs.setText("banco de dados");
        menuCRUDs.addActionListener(this::menuCRUDsActionPerformed);

        menuItemFuncionarios.setText("funcionario");
        menuItemFuncionarios.addActionListener(this::menuItemFuncionariosActionPerformed);
        menuCRUDs.add(menuItemFuncionarios);

        menuItemMercadorias.setText("mercadoria");
        menuItemMercadorias.addActionListener(this::menuItemMercadoriasActionPerformed);
        menuCRUDs.add(menuItemMercadorias);

        menuItemSenha.setText("alterar senha");
        menuItemSenha.addActionListener(this::menuItemSenhaActionPerformed);
        menuCRUDs.add(menuItemSenha);

        jMenuBar2.add(menuCRUDs);

        menuRelatorios.setText("relatórios");

        menuItemRelatorioEstoque.setText("estoque");
        menuRelatorios.add(menuItemRelatorioEstoque);

        menuItemRelatoriovendas.setText("vendas");
        menuItemRelatoriovendas.addActionListener(this::menuItemRelatoriovendasActionPerformed);
        menuRelatorios.add(menuItemRelatoriovendas);

        menuItemRelatorioFinanceiro.setText("financeiro");
        menuRelatorios.add(menuItemRelatorioFinanceiro);

        jMenuBar2.add(menuRelatorios);

        jMenu1.setText("venda");

        menuItemVendas.setText("Abrir tela de vendas");
        jMenu1.add(menuItemVendas);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //banco de dados -> funcionario
    private void menuCRUDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCRUDsActionPerformed

    }//GEN-LAST:event_menuCRUDsActionPerformed

    private void menuItemRelatoriovendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatoriovendasActionPerformed
        
    }//GEN-LAST:event_menuItemRelatoriovendasActionPerformed

    private void menuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionariosActionPerformed
        CRUDFuncionariosFrame CRUDFuncionarios = new CRUDFuncionariosFrame(this.funcionarioLogado);
        jDesktopPane1.add(CRUDFuncionarios);
        CRUDFuncionarios.setVisible(true);
    }//GEN-LAST:event_menuItemFuncionariosActionPerformed

    private void menuItemMercadoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMercadoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemMercadoriasActionPerformed

    private void menuItemSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSenhaActionPerformed
        AlterarSenhaFrame alterarSenha = new AlterarSenhaFrame(this.funcionarioLogado);
        jDesktopPane1.add(alterarSenha);
        alterarSenha.setVisible(true);
    }//GEN-LAST:event_menuItemSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuCRUDs;
    private javax.swing.JMenuItem menuItemFuncionarios;
    private javax.swing.JMenuItem menuItemMercadorias;
    private javax.swing.JMenuItem menuItemRelatorioEstoque;
    private javax.swing.JMenuItem menuItemRelatorioFinanceiro;
    private javax.swing.JMenuItem menuItemRelatoriovendas;
    private javax.swing.JMenuItem menuItemSenha;
    private javax.swing.JMenuItem menuItemVendas;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables
}
