package view;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import model.domain.Funcionario;
import model.domain.TipoUsuario;
import model.database.DatabaseConnection;

public class TelaPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName());

    private Funcionario funcionarioLogado;
    
    public TelaPrincipalFrame(Funcionario funcionario) {
        initComponents();
        setLocationRelativeTo(null);
        this.funcionarioLogado = funcionario;
        boolean isAdmin = this.funcionarioLogado.getTipoUsuario() == TipoUsuario.ADMINISTRADOR;
        menuItemFuncionarios.setVisible(isAdmin);
        menuItemMercadorias.setVisible(isAdmin);
        menuRelatorios.setVisible(isAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuCRUDs = new javax.swing.JMenu();
        menuItemFuncionarios = new javax.swing.JMenuItem();
        menuItemMercadorias = new javax.swing.JMenuItem();
        menuItemSenha = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuItemRelatorioEstoque = new javax.swing.JMenuItem();
        menuItemRelatoriovendas = new javax.swing.JMenuItem();
        menuItemRelatorioVendasDetalhado = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        menuCRUDs.setText("banco de dados");
        menuCRUDs.addActionListener(this::menuCRUDsActionPerformed);

        menuItemFuncionarios.setText("funcionario");
        menuItemFuncionarios.addActionListener(this::menuItemFuncionariosActionPerformed);
        menuCRUDs.add(menuItemFuncionarios);

        menuItemMercadorias.setText("mercadoria");
        menuItemMercadorias.addActionListener(this::menuItemMercadoriasActionPerformed);
        menuCRUDs.add(menuItemMercadorias);

        menuItemSenha.setText("alterar senha");
        menuItemSenha.addActionListener(this::menuItemSenhaActionPerformed);
        menuCRUDs.add(menuItemSenha);

        jMenuBar2.add(menuCRUDs);

        menuRelatorios.setText("relatórios");

        menuItemRelatorioEstoque.setText("estoque");
        menuItemRelatorioEstoque.addActionListener(this::menuItemRelatorioEstoqueActionPerformed);
        menuRelatorios.add(menuItemRelatorioEstoque);

        menuItemRelatoriovendas.setText("vendas");
        menuItemRelatoriovendas.addActionListener(this::menuItemRelatoriovendasActionPerformed);
        menuRelatorios.add(menuItemRelatoriovendas);

        menuItemRelatorioVendasDetalhado.setText("vendas detalhado");
        menuItemRelatorioVendasDetalhado.addActionListener(this::menuItemRelatorioVendasDetalhadoActionPerformed);
        menuRelatorios.add(menuItemRelatorioVendasDetalhado);

        jMenuBar2.add(menuRelatorios);

        jMenu1.setText("venda");

        menuItemVendas.setText("Abrir tela de vendas");
        menuItemVendas.addActionListener(this::menuItemVendasActionPerformed);
        jMenu1.add(menuItemVendas);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //banco de dados -> funcionario
    private void menuCRUDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCRUDsActionPerformed

    }//GEN-LAST:event_menuCRUDsActionPerformed

    private void menuItemRelatoriovendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatoriovendasActionPerformed
        String dataInicioStr = JOptionPane.showInputDialog(this, 
            "Data início (dd/MM/yyyy):", "Período", JOptionPane.QUESTION_MESSAGE);
        if (dataInicioStr == null) return;

        String dataFimStr = JOptionPane.showInputDialog(this, 
            "Data fim (dd/MM/yyyy):", "Período", JOptionPane.QUESTION_MESSAGE);
        if (dataFimStr == null) return;

        try {
            java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            java.sql.Timestamp dataInicio = java.sql.Timestamp.valueOf(java.time.LocalDate.parse(dataInicioStr, fmt).atStartOfDay());
            java.sql.Timestamp dataFim = java.sql.Timestamp.valueOf(java.time.LocalDate.parse(dataFimStr, fmt).atTime(23, 59, 59));

            Connection conn = DatabaseConnection.getConnection();
            InputStream stream = getClass().getResourceAsStream("/relatorios/RelatorioVendas.jasper");

            Map<String, Object> parametros = new HashMap<>();
            parametros.put("data_inicio", dataInicio);
            parametros.put("data_fim", dataFim);

            JasperPrint jasperPrint = JasperFillManager.fillReport(stream, parametros, conn);
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setTitle("Relatório de Vendas");
            viewer.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro de relatório: " + e.getMessage());
        }        
    }//GEN-LAST:event_menuItemRelatoriovendasActionPerformed

    private void menuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionariosActionPerformed
        CRUDFuncionariosFrame CRUDFuncionarios = new CRUDFuncionariosFrame(this.funcionarioLogado);
        jDesktopPane1.add(CRUDFuncionarios);
        CRUDFuncionarios.setVisible(true);
    }//GEN-LAST:event_menuItemFuncionariosActionPerformed

    private void menuItemMercadoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMercadoriasActionPerformed
        CRUDMercadoriasFrame CRUDMercadorias = new CRUDMercadoriasFrame();
        jDesktopPane1.add(CRUDMercadorias);
        CRUDMercadorias.setVisible(true);
    }//GEN-LAST:event_menuItemMercadoriasActionPerformed

    private void menuItemSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSenhaActionPerformed
        AlterarSenhaFrame alterarSenha = new AlterarSenhaFrame(this.funcionarioLogado);
        jDesktopPane1.add(alterarSenha);
        alterarSenha.setVisible(true);
    }//GEN-LAST:event_menuItemSenhaActionPerformed

    private void menuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendasActionPerformed
        VendasFrame Vendas = new VendasFrame(this.funcionarioLogado);
        jDesktopPane1.add(Vendas);
        Vendas.setVisible(true);
    }//GEN-LAST:event_menuItemVendasActionPerformed

    private void menuItemRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioEstoqueActionPerformed
        try {
            Connection conn = DatabaseConnection.getConnection();
            InputStream stream = getClass().getResourceAsStream("/relatorios/relatorioEstoque.jasper");

            Map<String, Object> parametros = new HashMap<>();

            JasperPrint jasperPrint = JasperFillManager.fillReport(stream, parametros, conn);
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setTitle("Relatório de Estoque Atual");
            viewer.setVisible(true);
        
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro de relatório: " + e.getMessage());
        }
    }//GEN-LAST:event_menuItemRelatorioEstoqueActionPerformed

    private void menuItemRelatorioVendasDetalhadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioVendasDetalhadoActionPerformed
        try {
            Connection conn = DatabaseConnection.getConnection();
            InputStream stream = getClass().getResourceAsStream("/relatorios/relatorioVendasDetalhado.jasper");

            Map<String, Object> parametros = new HashMap<>();

            JasperPrint jasperPrint = JasperFillManager.fillReport(stream, parametros, conn);
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setTitle("Relatório de Vendas");
            viewer.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro de relatório: " + e.getMessage());
        }
    }//GEN-LAST:event_menuItemRelatorioVendasDetalhadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuCRUDs;
    private javax.swing.JMenuItem menuItemFuncionarios;
    private javax.swing.JMenuItem menuItemMercadorias;
    private javax.swing.JMenuItem menuItemRelatorioEstoque;
    private javax.swing.JMenuItem menuItemRelatorioVendasDetalhado;
    private javax.swing.JMenuItem menuItemRelatoriovendas;
    private javax.swing.JMenuItem menuItemSenha;
    private javax.swing.JMenuItem menuItemVendas;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables
}
